import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!user.isSignedIn && (
          <SignInButton>
            <button className="rounded-md bg-[#2e026d] px-4 py-2 text-white">
              Sign in
            </button>
          </SignInButton>
        )}
        {!!user.isSignedIn && (
          <SignOutButton>
            <button className="rounded-md bg-gray-700 px-4 py-2 text-white">
              Sign out
            </button>
          </SignOutButton>
        )}

        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
